### ISSUE TITLE
libstdc++.so.6: no version information available (required by ampinstmgr)

### ISSUE THREAD

**Issue by zazou1998** [imagegenius/docker-amp#15]
hello,

i have an issue with this docker(alpine version and ubuntu) when i start it after apdating it he throw me this error message :

ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.TextInfo..cctor()
   at System.Diagnostics.Tracing.EventSource.GetGuid(System.Type)
   at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
   at System.Net.NetEventSource..cctor()
   at System.Net.Http.HttpMessageHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at ModuleShared.Utilities..cctor()
   at ModuleShared.Utilities.LogProcArgs(System.Diagnostics.ProcessStartInfo)
   at ModuleShared.Utilities.GetUtilityOutput(System.String, System.String, System.String, System.String, Boolean, Int32, System.String)
   at ModuleShared.MiniPlatformInfo.GetArch()
   at ModuleShared.MiniPlatformInfo..ctor()
   at InstanceManagerCLI.Core..ctor()
   at InstanceManagerCLI.Program.<Main>()
./run: line 3:   302 Aborted                 s6-setuidgid abc ampinstmgr StartBoot
[custom-init] No custom files found, skipping...

could you help me resolving this issue? 

kind regards

**Comment by zazou1998** [comment]
To resolve my issue temporarily, I ran this command: apk update && apk add --no-cache icu-libs libstdc++.

**Comment by hydazz** [comment]
can you try `ghcr.io/imagegenius/igpipepr-amp:2.6.0-pr-17`

**Comment by zazou1998** [comment]
The issue persists.

Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.TextInfo..cctor()
   at System.Diagnostics.Tracing.EventSource.GetGuid(System.Type)
   at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
   at System.Net.NetEventSource..cctor()
   at System.Net.Http.HttpMessageHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at ModuleShared.Utilities..cctor()
   at ModuleShared.Utilities.LogProcArgs(System.Diagnostics.ProcessStartInfo)
   at ModuleShared.Utilities.GetUtilityOutput(System.String, System.String, System.String, System.String, Boolean, Int32, System.String)
   at ModuleShared.MiniPlatformInfo.GetArch()
   at ModuleShared.MiniPlatformInfo..ctor()
   at InstanceManagerCLI.Core..ctor()
   at InstanceManagerCLI.Program.<Main>()
./run: line 12:  3662 Aborted                 s6-setuidgid abc ampinstmgr StartBoot
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)
ampinstmgr: /usr/lib/libstdc++.so.6: no version information available (required by ampinstmgr)

![Capture d'écran 2024-10-31 123638](https://github.com/user-attachments/assets/ec609076-1543-47d2-a4c6-f411ba9b2ac5)

**Comment by hydazz** [comment]
sorry, wrong tag. try `ghcr.io/imagegenius/igpipepr-amp:2.6.0-PR-16`

**Comment by zazou1998** [comment]
this one work perfectly thanks a lot

**Comment by hydazz** [comment]
epic, ill merge with main, switch back to the old tag in a few minutes
